
export { default as Login } from "../pages/Login.jsx"
export { default as Signup } from "../pages/Signup.jsx"
export { default as Home } from "../pages/home.jsx"
export { default as CreateProduct } from "../pages/createProduct.jsx"
export { default as MyProducts } from "../pages/myProducts.jsx"
export { default as Cart } from "../pages/cart.jsx"
export { default as ProductDetails } from "../pages/productDetails.jsx"
export { default as Profile } from "../pages/profile.jsx"
export { default as CreateAddress } from "../pages/createAddress.jsx"
export { default as SelectAddress } from "../pages/SelectAddress.jsx"
export { default as OrderConfirmation } from "../pages/OrderConfirmation.jsx"
export { default as Myorders } from "../pages/myorders.jsx"